### ISSUE TITLE
Add dicty-header

### ISSUE THREAD

**Issue by haridusenadeera** [dictyBase/dicty-react-components#18]
# HTML

```
<div class="container-fluid">
    <div class="row center-xs start-sm bottom-sm" >
        <div class="col-xs-12 col-sm-4 col-lg-3 col-lg-offset-1">
          dictyBase Logo
        </div>
        <div class="col-xs-12 col-sm-8 col-lg-7" >
            <div class="row center-xs end-sm">
                <div class="col-xs-12">
                   <ul>
                     <li><a href="#">Cite Us</a></li>
                     <li><a href="#">Downloads</a></li>
                     <li><a href="#">About Us</a></li>
                     <li><a href="#">Contact</a></li>
                     <li><a href="#">Login</a></li>
                   </ul>
                </div>
            </div>
            <div class="row center-xs end-sm">
                <div class="col-xs-12 col-sm-8 col-md-6">Search Box</div>
            </div>
        </div>
    </div>
</div>
```

**Comment by cybersiddhu** [comment]
Approaches for header
- Use flexbox grid. To use that integrate css files into webpack. 
  - For that use webpack's css loader.

**Comment by haridusenadeera** [comment]
#### ToDo
- [x] Make the layout for dicty-header
  - [x] Use flexbox for the layout
- [x] Checkout a new branch from `develop` branch to add dicty-header
- [x] Integrate CSS files in webpack
  - [x] Use webpack CSS loader

**Comment by haridusenadeera** [comment]
# Flexbox Layout

![header-layout](https://cloud.githubusercontent.com/assets/12897928/10851034/d451da84-7ef6-11e5-88d4-b96153e7c725.jpg)

**Comment by haridusenadeera** [comment]
Importing flexbox grid using webpack css loader: 9a09631e3890134daed2c035c3f887532f7091b5 & 8266fb2c2a5ed0561a1777f9b1bc87beb4de19f7
